name: phoebe
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - ase
  - pymatgen
  - phonopy
  - phono3py
  - spglib
  - seekpath
  - h5py
  - pyyaml
  - openpyxl
